INSERT INTO productos (cantidad,nombre,color,marca,codigo,categoria) VALUES
(3,'Cartón de presentación','Negro','Variadas',531,'Cartulinas'),
(2,'Cartón de Presentación','Blanco','Facela',532,'Cartulinas'),
(3,'Cartulina','Surtido','Búho',535,'Cartulinas'),
(5,'Cartulina','Surtido','Koala',536,'Cartulinas'),
(4,'Cartulina Bristol','Blanco','Búho',537,'Cartulinas'),
(2,'Cartulina Bristol','Negro','Búho',538,'Cartulinas'),
(1,'Cartulina Bristol','Surtidos','Copy Vision',539,'Cartulinas'),
(1,'Cartulina de bicicleta grande','Morado','Variado',540,'Cartulinas'),
(15,'Cartulina de unicornio grande','Rosado','Variado',541,'Cartulinas'),
(7,'Cartulina grande','Amarillo','Variado',542,'Cartulinas'),
(12,'Cartulina grande','Anaranjado','Variado',543,'Cartulinas'),
(2,'Cartulina Grande','Azul Néon ','Variado',544,'Cartulinas'),
(6,'Cartulina Grande','Rosa Néon','Variado',545,'Cartulinas'),
(2,'Cartulina Grande','Rosa Pastel','Variado',546,'Cartulinas'),
(3,'Cartulina Grande','Verde Oscuro','Variado',547,'Cartulinas'),
(2,'Cartulina Grande','Negro','Variado',548,'Cartulinas'),
(1,'Cartulina Grande','Café','Variado',549,'Cartulinas'),
(1,'Cartulina Grande','Amarillo Néon','Variado',550,'Cartulinas'),
(3,'Cartulina Grande','Celeste','Variado',551,'Cartulinas'),
(1,'Cartulina Grande','Celeste Pastel','Variado',552,'Cartulinas'),
(1,'Cartulina Grande','Lila','Variado',553,'Cartulinas'),
(7,'Cartulina Néon','Surtido','Búho',554,'Cartulinas'),
(2,'Cartulina Pequeña','Rosada ','Variado',555,'Cartulinas'),
(3,'Cartulina Pequeña','Verde','Variado',556,'Cartulinas'),
(1,'Cartulina Pequeña','Blanco ','Variado',557,'Cartulinas'),
(7,'Cartulina Tamaño Carta','Amarillo','Karyma',558,'Cartulinas'),
(1,'Cartulina Tamaño Carta','Negro','Karyma',559,'Cartulinas'),
(1,'Cartulina Tamaño Carta','Negro','Variadas',560,'Cartulinas'),
(1,'Cartulinas Perlada','Surtido','Variado',561,'Cartulinas'),
(0,'Cartulina Lino','Todos los colores','Búho',826,'Cartulinas'),
(0,'Cartulina Regular','Todos los colores','Sin marca',827,'Cartulinas'),
(0,'Cartulina Satinada','Todos los colores','Sin marca',828,'Cartulinas'),
(1,'Cuaderno de Caligrafía','Verde','Rider',577,'Cuaderno'),
(1,'Cuaderno de Caligrafía','Anaranjado','Union Olé',578,'Cuaderno'),
(8,'Cuaderno de Caligrafía','Variado','Ventura',579,'Cuaderno'),
(6,'Cuaderno de Caligrafía','Morado','Búho',580,'Cuaderno'),
(7,'Cuaderno de Caligrafía','Variado','Nottas',581,'Cuaderno'),
(1,'Cuaderno de Dibujo','Verde','SD',582,'Cuaderno'),
(12,'Cuaderno Rayado','Variado','MEP',583,'Cuaderno'),
(5,'Cuaderno Rayado','Variado','Nottas',584,'Cuaderno'),
(3,'Libro "Aprendo a valerme x mi mismo" I grado','Surtido','iafa',660,'Cuaderno'),
(0,'Actas (1 libro)','Varia','Sin marca',801,'Cuaderno'),
(1,'Adaptador de HDMI a VGA','Negro','Unno',501,'Electronica'),
(1,'Audifonos de casco','Negro','Sharkoon',506,'Electronica'),
(2,'Estuches para tablets','Negros','Sin Marca',594,'Electronica'),
(1,'Guillotina','Gris','KW-Trio',621,'Electronica'),
(1,'Interructor automatico','Negro','Qwi-K-Gard',626,'Electronica'),
(1,'Megáfono','Blanco y Rojo','Sin Marca',675,'Electronica'),
(1,'Parlante','Negro','Argom',698,'Electronica'),
(2,'Parlantes grandes','Negro','Flame-led',699,'Electronica'),
(4,'Parlantes pequeños','Negro','Argomtech',700,'Electronica'),
(5,'Pistola de Silicón','Amarillo','Jappy',719,'Electronica'),
(1,'Plancha convencional','Negro','Black-Decker',721,'Electronica'),
(1,'Plancha de vapor','Celeste','Black-Decker',722,'Electronica'),
(1,'Regleta','Amarillo','Forza',738,'Electronica'),
(1,'Soporte de microfono','Negro','Shure',755,'Electronica'),
(1,'Soporte de pantalla','Negro','Basic-Living',756,'Electronica'),
(4,'VideoBin','Negro','Variado',787,'Electronica'),
(5,'Calculadora','Negro','Casio MX-8B',824,'Electronica'),
(3,'Caculadora','Negro','Casio MX-12B-BK',825,'Electronica'),
(13,'Ampos','Negro','AMPO',505,'Folders'),
(2,'Carpetas Colgantes de Ampo','Café','AMPO',530,'Folders'),
(2,'Folder','Surtido','Irasa',596,'Folders'),
(1,'Folders Tamaño Carta','Amarillo','Facela',597,'Folders'),
(1,'Folders tamaño carta','Amarillo','Irasa',598,'Folders'),
(1,'Folders tamaño carta','Negro','Irasa',599,'Folders'),
(5,'Sobre blanco #10','Blanco','Sin Marca',750,'Folders'),
(1,'Sobre blanco #6','Blanco ','Sin Marca',751,'Folders'),
(3,'Sobre Manila #13','Amarillo','Búho',752,'Folders'),
(3,'Sobre Manila #15','Amarillo','Búho',753,'Folders'),
(6,'Sobre Manila Tipo Carta','Amarillo','Búho',754,'Folders'),
(71,'Sujetadores de Folder','Gris','Artline',761,'Folders'),
(3,'Bolsas de laminación termica','Blanco','Studmark',514,'Hojas'),
(1,'Celofán','Surtido','Variado',562,'Hojas'),
(2,'Forro Adhesivo de libros','Blanco','Sadipal',600,'Hojas'),
(2,'Fundas para hojas','Blanco ','Karyma',601,'Hojas'),
(2,'Fundas para laminar','Blanco','Karyma',602,'Hojas'),
(1,'Hojas Cuadriculadas para portafolio','Rayadas','MED',622,'Hojas'),
(22,'Hojas de cartulina','Surtido','Varias',623,'Hojas'),
(1,'Lamina de fieltro','Gris','Sin Marca',633,'Hojas'),
(1,'Lamina de fieltro','Rosa','Sin Marca',634,'Hojas'),
(1,'Lamina de fieltro','Lila','Sin Marca',635,'Hojas'),
(1,'Lamina de fieltro','Café','Sin Marca',636,'Hojas'),
(1,'Lamina de fieltro','Verde','Sin Marca',637,'Hojas'),
(1,'Láminas para plasticado','Blanco','Studmark',638,'Hojas'),
(13,'Papel Construcción','Surtido','Maped',682,'Hojas'),
(24,'Papel Crepe','Blanco','Búho',683,'Hojas'),
(19,'Papel Crepe','Rosado','Búho',684,'Hojas'),
(40,'Papel Crepe','Café ','Búho',685,'Hojas'),
(2,'Papel Crepe','Verde ','Búho',686,'Hojas'),
(5,'Papel Crepe','Rojos','Búho',687,'Hojas'),
(1,'Papel Crepe','Celeste','Búho',688,'Hojas'),
(1,'Papel Crepe','Lila','Facela',689,'Hojas'),
(14,'Papel Crepe','Azúl','Facela',690,'Hojas'),
(26,'Papel Crepe','Azúl Rey','Búho',691,'Hojas'),
(1,'Papel Crepe','Amarillo','Variado',692,'Hojas'),
(17,'Papel Crepe','Anaranjado','Búho',693,'Hojas'),
(3,'Papel Foam','Variados','Studmark',694,'Hojas'),
(7,'Papel Fotografico Adhesivo A4','Surtido','Merletto',695,'Hojas'),
(4,'Papel Ledger','Blanco ','Búho',696,'Hojas'),
(6,'Resmas de papel','Blanco','Falcon',740,'Hojas'),
(0,'Papel de regalo','Papel de regalo','Sin marca',817,'Hojas'),
(0,'Papel de regalo','Blanco','Sin marca',818,'Hojas'),
(0,'Papel de regalo','Celeste','Sin marca',819,'Hojas'),
(0,'Papel de regalo','Azul','Sin marca',820,'Hojas'),
(0,'Papel de regalo','Morado','Sin marca',821,'Hojas'),
(0,'Papel de regalo','Rosado','Sin marca',822,'Hojas'),
(0,'Papel de regalo','Amarillo','Sin marca',823,'Hojas'),
(0,'Papel Celofán','12 colores','Sin marca',839,'Hojas'),
(3,'Papel Fotografico Brillante','Blanco','Ventura',840,'Hojas'),
(1,'Papel fotografico Brillante','Blanco','Sin marca',841,'Hojas'),
(5,'Papel fotografico Brillante','Blanco','Studmark',842,'Hojas'),
(1,'Caja de sello automática','Negro','KW-triO',528,'Tintas'),
(3,'Impresora Modelo L3250','Negro','EPSON',624,'Tintas'),
(10,'Recarga de Tinta para plumón de pizarra','Rojo','Artline',730,'Tintas'),
(5,'Recarga de Tinta para plumón de pizarra','Negro','Artline',731,'Tintas'),
(3,'Recarga de Tinta para plumón de pizarra','Verde','Artline',732,'Tintas'),
(2,'Tinta BK190 CANON','Negro','CANON',765,'Tintas'),
(5,'Tinta C10 CANON','Azul','CANON',766,'Tintas'),
(13,'Tinta C16 CANON','Azul','CANON',767,'Tintas'),
(9,'Tinta EPSON 504','Azul','EPSON',768,'Tintas'),
(12,'Tinta EPSON 504','Negro','EPSON',769,'Tintas'),
(2,'Tinta EPSON 504','Amarilla','EPSON',770,'Tintas'),
(10,'Tinta EPSON 544','Magenta','EPSON',771,'Tintas'),
(7,'Tinta EPSON 544','Amarillo','EPSON',772,'Tintas'),
(13,'Tinta EPSON 664','Magenta','EPSON',773,'Tintas'),
(15,'Tinta EPSON 664','Amarilla','EPSON',774,'Tintas'),
(11,'Tinta EPSON 664','Negro','EPSON',775,'Tintas'),
(13,'Tinta EPSON 664','Azul','EPSON',776,'Tintas'),
(4,'Tinta M10 CANON','Magenta','CANON',777,'Tintas'),
(13,'Tinta M16 CANON','Magenta','CANON',778,'Tintas'),
(7,'Tinta M190 CANON','Magenta','CANON',779,'Tintas'),
(9,'Tinta para sello','Azul ','Artline',780,'Tintas'),
(7,'Tinta para sello','Negro','Artline',781,'Tintas'),
(5,'Tinta Y10 CANON','Amarilla','CANON',782,'Tintas'),
(13,'Tinta Y16 CANON','Amarillo','CANON',783,'Tintas'),
(0,'Almuadillas de sellos','Varían','Sin marca',796,'Tintas'),
(2,'Acuarelas Minis','Varia','Sin Marca',500,'Utiles'),
(105,'Barras de Silicón delgadas','Blanco','Resistol',510,'Utiles'),
(88,'Barras de Silicón gruesas','Blanco','Búho',511,'Utiles'),
(0,'Borrador de Pizarra','Rojo','Artline',515,'Utiles'),
(24,'Borradores','Surtido','Stabilo',516,'Utiles'),
(13,'Brillantina','Verde','Studmark',521,'Utiles'),
(9,'Brillantina','Rojo','Studmark',522,'Utiles'),
(6,'Brillantina','Azul','Studmark',523,'Utiles'),
(1,'Brillantina','Plateado','Studmark',524,'Utiles'),
(4,'Brochas','Rojo','Sargent Artist',525,'Utiles'),
(3,'Brochas','Blanco','Studmark',526,'Utiles'),
(1,'Brochas para pintar','Rojo','Sin Marca',527,'Utiles'),
(2,'Cartuchos de Cinta S015329','Negro','Epson Fx-890',534,'Utiles'),
(3,'Chinches / Tachuelas','Gris','Warrior',564,'Utiles'),
(13,'Cinta adhesiva estandar','Blanco','Tesa-Film',565,'Utiles'),
(1,'Cinta de empaque','Gris','Scotch',566,'Utiles'),
(3,'Clips  33mm"','Variado','Warrior',567,'Utiles'),
(10,'Clips  33mm"','Variado','Karyma',568,'Utiles'),
(7,'Clips  50mm"','Variado','Facela',569,'Utiles'),
(4,'Crayon de cera JUMBO','Surtido','Deli',574,'Utiles'),
(2,'Crayones de cera','Variado','PeliKan',575,'Utiles'),
(4,'Crayones de cera JUMBO','Surtido','Faber-Castell',576,'Utiles'),
(2,'Cutter','Negro','Studmark',586,'Utiles'),
(1,'Dispensador de cinta','Negro ','Decavisa',589,'Utiles'),
(1,'Dispensador manual de cinta','Gris','3M',590,'Utiles'),
(1,'Elastico','Blanco','Variado',591,'Utiles'),
(5,'Engrapadora','Negro','Variado',592,'Utiles'),
(2,'Engrapadora de Uso Pesado','Negro','Studmark',593,'Utiles'),
(3,'Gomas en barra','Variado','Variado',618,'Utiles'),
(2,'Grapas (23/13)','Gris','KW-triO',619,'Utiles'),
(19,'Grapas (26/6)','Gris','Variado',620,'Utiles'),
(4,'Lapiceros ','Negro','Faber-Castel',641,'Utiles'),
(15,'Lapiceros ','Rojo','BIC',642,'Utiles'),
(4,'Lapiceros Azul','Azul','Inoxcrom',643,'Utiles'),
(5,'Lapiceros en Combo','Rojo, Azul, Negro','D´Notas',644,'Utiles'),
(23,'Lapiceros Negros','Negros','Inoxcrom',645,'Utiles'),
(38,'Lapiceros Rojos','Rojos','Inoxcrom',646,'Utiles'),
(17,'Lapices de color','Variado','Kores',647,'Utiles'),
(9,'Lapices de color','Variado','Faber - Castel',648,'Utiles'),
(1,'Lapices de color','Variado','Faber - Castel',649,'Utiles'),
(29,'Lapices de color','Variado','Kores',650,'Utiles'),
(4,'Lapices de color','Variado','Maped',651,'Utiles'),
(2,'Lapices de color','Variado','D''Notas',652,'Utiles'),
(22,'Lapices de escribir','Amarillo','Faber - Castel',653,'Utiles'),
(12,'Lapiz de color','Variado','Kores',654,'Utiles'),
(8,'Lapiz de escribir','Amarillo','Facela',655,'Utiles'),
(40,'Lapiz de escribir','Amarillo','Mongol',656,'Utiles'),
(2,'Lapiz de escribir ','Amarillo','D'' Notas',657,'Utiles'),
(9,'Lapiz de escribir JUMBO','Anaranjado','Maped',658,'Utiles'),
(4,'Lapiz de escribir JUMBO','Rojos','Kores',659,'Utiles'),
(1,'Ligas de Hule No.10','Gris','MAE',661,'Utiles'),
(59,'Limpiapipas','Variado','Variado',662,'Utiles'),
(1,'Maquinilla Electronica','Negro','Studmark',663,'Utiles'),
(21,'Maquinillas','Surtido','Maped',664,'Utiles'),
(18,'Marcador de pizarra','Rojo','Variado',665,'Utiles'),
(12,'Marcador de pizarra','Verde','Variado',666,'Utiles'),
(7,'Marcador de pizarra','Negro','Variado',667,'Utiles'),
(8,'Marcador de pizarra','Azul','Variado',668,'Utiles'),
(2,'Marcador de pizarra Permanente','Negro','Variado',669,'Utiles'),
(1,'Marcador de pizarra Permanente','Rojo','Variado',670,'Utiles'),
(1,'Marcador de pizarra Permanente','Verde','Variado',671,'Utiles'),
(2,'Marcador de pizarra Permanente','Azul','Variado',672,'Utiles'),
(3,'Marcadores de Plumón','Surtido','Norma',673,'Utiles'),
(12,'Minas','Gris','Faber-Castel',676,'Utiles'),
(2,'Notas Adhesivas','Surtido','Studmark',677,'Utiles'),
(1,'Paleta de madera "100 x 100"','Café','Búho',679,'Utiles'),
(42,'Paletas de Colores','Vario','Sin Marca',680,'Utiles'),
(3,'Paletas de madera 100x100','Café','Búho',681,'Utiles'),
(3.78,'Pegamento','Blanco','Resistol',701,'Utiles'),
(3,'Pines 9mm"','Variado','Studmark',702,'Utiles'),
(5,'Pintuas de dedos','Variados','Javi',703,'Utiles'),
(7,'Pintura Acrilica','Rojos','Variado',704,'Utiles'),
(9,'Pintura Acrilica','Anaranjado','Variado',705,'Utiles'),
(7,'Pintura Acrilica','Amarillo','Variado',706,'Utiles'),
(2,'Pintura Acrilica','Rosado','Variado',707,'Utiles'),
(4,'Pintura Acrilica','Verde Claro','Variado',708,'Utiles'),
(4,'Pintura Acrilica','Verde Oscuro','Variado',709,'Utiles'),
(4,'Pintura Acrilica','Gris','Variado',710,'Utiles'),
(1,'Pintura Acrilica','Café ','Variado',711,'Utiles'),
(1,'Pintura Acrilica','Dorado','Variado',712,'Utiles'),
(4,'Pintura Acrilica','Lila','Variado',713,'Utiles'),
(2,'Pintura Acrilica','Morado','Variado',714,'Utiles'),
(3,'Pintura Acrilica','Blanco','Variado',715,'Utiles'),
(2,'Pintura Acrilica','Azúl','Variado',716,'Utiles'),
(6,'Pintura Acrilica','Negro','Variado',717,'Utiles'),
(2,'Pinturas en tempera','Variado','Faber-Castel',718,'Utiles'),
(4,'Plastilina','Variado','Play-Doh',724,'Utiles'),
(5,'Portalapices de guía','Surtido','Deli',725,'Utiles'),
(4,'Quitagrapas','Negro','Deli',728,'Utiles'),
(13,'Quitagrapas','Negro','KW-Trio',729,'Utiles'),
(1,'Regla 18 pulgadas','Blanco','Supreme',733,'Utiles'),
(10,'Regla rosa de los vientos','Azul','Baco',734,'Utiles'),
(3,'Reglas de plástico 30cm','Blanco','Varios',735,'Utiles'),
(11,'Reglas Transportadoras de 180°','Varios','Varios',736,'Utiles'),
(10,'Reglas Triangulares','Varios','Varios',737,'Utiles'),
(2,'Resaltadores','Variado','Deli',739,'Utiles'),
(2,'Sacabocados','Negro Gris','Studmark',744,'Utiles'),
(8,'Sacabocados','Negro ','Studmark',745,'Utiles'),
(1,'Sacabocados manual','Blanco','Sin Marca',746,'Utiles'),
(2,'Silicón Líquido','Blanco','Resistol',747,'Utiles'),
(2,'Silicón Líquido','Blanco','Studmark',748,'Utiles'),
(1,'Silicón Líquido','Blanco','Búho',749,'Utiles'),
(25,'Sujetadores / Fastener','Surtidos','Warrior',759,'Utiles'),
(7,'Sujetadores / Fastener','Surtidos','Karyma',760,'Utiles'),
(8,'Tape Invisible','Variado','Studmark',762,'Utiles'),
(1,'Tijera Diestro','Azul','Studmark',763,'Utiles'),
(4,'Tijeras Zurdos','Variado','Maped',764,'Utiles'),
(1,'Tizas','Variado','MUNGYO',784,'Utiles'),
(4,'Tizas en barra','Variado','Rodart',785,'Utiles'),
(0,'Cinta doble cara','Sin Color','Sin marca',788,'Utiles'),
(0,'Cinta doble cara','Blanca','Sin marca',789,'Utiles'),
(0,'Masking tape','Blanco','Sin marca',790,'Utiles'),
(0,'Grapadoras','Varían','Sin marca',791,'Utiles'),
(0,'Sacabocado individual','Varían','Sin marca',792,'Utiles'),
(0,'Plumas negras en gel','Negro','Sin marca',793,'Utiles'),
(0,'Plumas azules en gel','Azul','Sin marca',794,'Utiles'),
(0,'Tisas','Blancas','Sin marca',795,'Utiles'),
(0,'Gomitas para contar las hojas','Varían','Sin marca',797,'Utiles'),
(0,'Goma líquida grande','Blancas','Pritt',798,'Utiles'),
(0,'Goma en barra grande','Blancas','Pritt',799,'Utiles'),
(0,'Mecate cabuya','Café','Sin marca',800,'Utiles'),
(0,'Cutter grande','Varia','Sin marca',802,'Utiles'),
(0,'Cutter pequeña','Varia','Sin marca',803,'Utiles'),
(0,'Tijera en picos','Varia','Sin marca',804,'Utiles'),
(0,'Cartel feria científica','Blanco','Sin marca',805,'Utiles'),
(0,'Cartel feria científica','Negro','Sin marca',806,'Utiles'),
(0,'Estereofón Lámina de 2 grosor','Blanco','Sin marca',807,'Utiles'),
(0,'Oasis (Flores)','Varia','Sin marca',808,'Utiles'),
(0,'Caja plástica grande','Sin Color','Sin marca',809,'Utiles'),
(0,'Caja plástica mediana','Sin Color','Sin marca',810,'Utiles'),
(0,'Caja plástica pequeñas','Sin Color','Sin marca',811,'Utiles'),
(0,'Cuchillas para cutter','Varia','Sin marca',812,'Utiles'),
(0,'Resaltadores','Naranja','Sin marca',813,'Utiles'),
(0,'Resaltadores','Amarillos','Sin marca',814,'Utiles'),
(0,'Resaltadores','Rosados','Sin marca',815,'Utiles'),
(0,'Resaltadores','Verdes','Sin marca',816,'Utiles'),
(0,'Cinta de arreglos fina','12 colores','Sin marca',829,'Utiles'),
(0,'Foami','Todos los colores','Sin marca',830,'Utiles'),
(0,'Maquinilla corriente (Sin Basurero)','Plateada','Sin marca',836,'Utiles'),
(0,'Marcadores gruesos de colores','Todos los colores','Sin marca',837,'Utiles'),
(0,'Notas Adhesivas','Todos los colores','Sin marca',838,'Utiles'),
(1,'Agujas','Gris','Variado',502,'Variado'),
(1,'Ajedrez 3 en 1','Variado','Sin Marca',503,'Variado'),
(73,'Alfileres','Variado','Variado',504,'Variado'),
(1,'Balón de Voleyball','Variado','Sin Marca',507,'Variado'),
(1,'Bandera del Catón','Variado','Sin Marca',508,'Variado'),
(4,'Banderas de Costa Rica','Variado','Sin Marca',509,'Variado'),
(2,'Bolas de estereofon-Grande','Blanco','Sin Marca',512,'Variado'),
(8,'Bolas estereofon-pequeñas','Blanco','Sin Marca',513,'Variado'),
(11,'Bridas Abiertas 4.8x350mm','Blanco','Casadream',517,'Variado'),
(45,'Bridas Abiertas 8x150mm','Blanco','Casadream',518,'Variado'),
(29,'Bridas Abiertas 8x200mm','Blanco','Casadream',519,'Variado'),
(20,'Bridas Abiertas 8x450mm','Blanco','Casadream',520,'Variado'),
(8,'Caña de Pescar','Gris','Brickell',529,'Variado'),
(1,'Cartucho de tinta AI-ET0621 18ml','Negro','AMIK',533,'Variado'),
(2,'Cepillos dentales de niño','Rojo','Colgate',563,'Variado'),
(2,'Conos de seguridad','Anaranjado','Varios',570,'Variado'),
(9,'Correas para gafete','Azul','Variadas',571,'Variado'),
(13,'Correas para gafete','Gris','Sin Marca',572,'Variado'),
(2,'Cortinas de decoración','Doradas','Sin Marca',573,'Variado'),
(1,'Cuatro en raya','Variado','Sin Marca',585,'Variado'),
(2,'Decoración flores','Rosadas','Sin Marca',587,'Variado'),
(6,'Decoración varia','Rosa','Sin Marca',588,'Variado'),
(3,'Extensiones','Variado','Variado',595,'Variado'),
(6,'Gazas','Doradas','Variado',603,'Variado'),
(2,'Gazas 28mm"','Plata','Motarro',604,'Variado'),
(8,'Gazas 32mm"','Plata','Motarro',605,'Variado'),
(1,'Gazas 43mm"','Plata','Motarro',606,'Variado'),
(2,'Globos','Rosa Brillante','PAYASO',607,'Variado'),
(2,'Globos','Café','RODIX',608,'Variado'),
(2,'Globos','Verde ','PAYASO',609,'Variado'),
(1,'Globos','Fucsia','PAYASO',610,'Variado'),
(1,'Globos','Anaranjado','PAYASO',611,'Variado'),
(1,'Globos','Azul Rey','RODIX',612,'Variado'),
(2,'Globos','Negro','PAYASO',613,'Variado'),
(1,'Globos','Blancos','PAYASO',614,'Variado'),
(1,'Globos','Rojos','RODIX',615,'Variado'),
(1,'Globos','Azul Cielo','PAYASO',616,'Variado'),
(1,'Globos','Amarillo','Variado',617,'Variado'),
(2,'Inflador de Globos','Amarillo','Variado',625,'Variado'),
(1,'Juego 3 en 1','Navio','Family Game ',627,'Variado'),
(1,'Juego de dominó','Variado','Sin Marca',628,'Variado'),
(10,'Juego de geometría','Blanco','Variado',629,'Variado'),
(1,'Juego líderes de prevención','Variado','Sin Marca',630,'Variado'),
(22,'Juegos de Jacsis','Variado','Sin Marca',631,'Variado'),
(2,'Juguemos Juntos','Anaranjados','MEP',632,'Variado'),
(3,'Lana','Morado','La chinita',639,'Variado'),
(1,'Lana','Celeste','La chinita',640,'Variado'),
(7,'Mascarillas Medicas','Celeste','Shou Hang Medical',674,'Variado'),
(1,'Ojos saltones','Blanco','Variado',678,'Variado'),
(1,'Paquete de Pintura Facial','Variado','MeiduGaga',697,'Variado'),
(80,'Placas de la Banda Escuela','Plata','Sin Marca',720,'Variado'),
(3,'Planos de la institución','Negro','Variado',723,'Variado'),
(3,'Portapapeles','Variado','Varios',726,'Variado'),
(4,'Portaplanos','Negro','Pointer',727,'Variado'),
(2,'Rollo de lana','Azul','Variado',741,'Variado'),
(1,'Rollo de lana','Blanco','Variado',742,'Variado'),
(1,'Rollo de Mecate','Café','Varios',743,'Variado'),
(4,'Stickers Grandes','Variado','Happy Stickers',757,'Variado'),
(4,'Stickers Pequeños','Variado','Happy Stickers',758,'Variado'),
(3,'Velcro','Blanco','Sin Marca',786,'Variado'),
(0,'Folder con laminas transparentes','Todos los colores','Sin marca',831,'Variado'),
(0,'Globos','Todos los colores','Sin marca',832,'Variado'),
(0,'Globos Largos','Todos los colores','Sin marca',833,'Variado'),
(2,'Juegos de geometria ','Sin Color','IMAS',834,'Variado'),
(8,'Juegos de geometria ','Sin color','D''Notas',835,'Variado');